# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/page_lcd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 580)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lcd_button_clear = QtWidgets.QPushButton(Form)
        self.lcd_button_clear.setGeometry(QtCore.QRect(770, 450, 150, 50))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_button_clear.setFont(font)
        self.lcd_button_clear.setStyleSheet("QPushButton:hover\n"
"{ \n"
"    background-color: rgb(0, 135, 68);\n"
"    border-radius: 15px;\n"
"    font: 75 20pt \"Arial\";\n"
"    color: white;  \n"
"}\n"
"\n"
"QPushButton\n"
"{ \n"
"    border-radius: 15px;\n"
"    border: 1px solid rgb(0, 135, 68);\n"
"    font: 75 20pt \"나눔스퀘어 Bold\";\n"
"    color: rgb(0, 135, 68);\n"
"}\n"
"")
        self.lcd_button_clear.setObjectName("lcd_button_clear")
        self.lcd_text = QtWidgets.QTextEdit(Form)
        self.lcd_text.setGeometry(QtCore.QRect(90, 80, 831, 331))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(50)
        self.lcd_text.setFont(font)
        self.lcd_text.setStyleSheet("")
        self.lcd_text.setObjectName("lcd_text")
        self.lcd_button_write = QtWidgets.QPushButton(Form)
        self.lcd_button_write.setGeometry(QtCore.QRect(600, 450, 150, 50))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 Bold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_button_write.setFont(font)
        self.lcd_button_write.setStyleSheet("QPushButton:hover\n"
"{ \n"
"    background-color: rgb(0, 135, 68);\n"
"    border-radius: 15px;\n"
"    font: 75 20pt \"Arial\";\n"
"    color: white;  \n"
"}\n"
"\n"
"QPushButton\n"
"{ \n"
"    border-radius: 15px;\n"
"    border: 1px solid rgb(0, 135, 68);\n"
"    font: 75 20pt \"나눔스퀘어 Bold\";\n"
"    color: rgb(0, 135, 68);\n"
"}\n"
"")
        self.lcd_button_write.setObjectName("lcd_button_write")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 40, 331, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lcd_button_clear.setText(_translate("Form", "Clear"))
        self.lcd_button_write.setText(_translate("Form", "Write"))
        self.label.setText(_translate("Form", "Enter the text to be printed on TextLCD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
