# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/page_terminal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 580)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.plain = QtWidgets.QPlainTextEdit(Form)
        self.plain.setGeometry(QtCore.QRect(70, 70, 851, 381))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.plain.setFont(font)
        self.plain.setStyleSheet("font: 14pt \"Consolas\";")
        self.plain.setReadOnly(True)
        self.plain.setObjectName("plain")
        self.input = QtWidgets.QLineEdit(Form)
        self.input.setGeometry(QtCore.QRect(170, 480, 751, 31))
        self.input.setStyleSheet("font: 12pt \"Consolas\";")
        self.input.setObjectName("input")
        self.cmd_label = QtWidgets.QLabel(Form)
        self.cmd_label.setGeometry(QtCore.QRect(80, 480, 71, 31))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cmd_label.setFont(font)
        self.cmd_label.setStyleSheet("background-color: white;\n"
"font: 81 20pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.cmd_label.setObjectName("cmd_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cmd_label.setText(_translate("Form", "cmd:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
