# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/page_option.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 860)
        Form.setStyleSheet("QWidget#Form\n"
"{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.camera_area = QtWidgets.QLabel(Form)
        self.camera_area.setGeometry(QtCore.QRect(275, 57, 1370, 782))
        self.camera_area.setStyleSheet("border-radius : 5px;\n"
"border: 8px solid rgb(0, 135, 68);\n"
"")
        self.camera_area.setText("")
        self.camera_area.setObjectName("camera_area")
        
        self.video_label = QtWidgets.QLabel(Form)
        self.video_label.setGeometry(QtCore.QRect(288, 70, 1344, 756))
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
