# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/page_sensing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):        
    def setupUi(self, Form):
        first_row = 140
        second_row = 740
        third_row = 1340
        
        first_column = 37
        second_column = 322
        third_column = 607
        
        Form.setObjectName("Form")
        Form.resize(1920, 860)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        
        self.sensor_in_temp = QtWidgets.QLabel(Form)
        #self.sensor_in_temp.setGeometry(QtCore.QRect(100, 50, 221, 121))
        self.sensor_in_temp.setGeometry(QtCore.QRect(first_row, first_column, 442, 242))
        self.sensor_in_temp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_in_temp.setText("")
        self.sensor_in_temp.setObjectName("sensor_in_temp")
        self.sensor_in_temp_value = QtWidgets.QLabel(Form)
        #self.sensor_in_temp_value.setGeometry(QtCore.QRect(110, 110, 201, 51))
        self.sensor_in_temp_value.setGeometry(QtCore.QRect(first_row + 10, first_column + 120, 402, 102))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_in_temp_value.setFont(font)
        self.sensor_in_temp_value.setStyleSheet("font: 81 35pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_in_temp_value.setText("")
        self.sensor_in_temp_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_temp_value.setObjectName("sensor_in_temp_value")
        self.sensor_in_temp_label = QtWidgets.QLabel(Form)
        #self.sensor_in_temp_label.setGeometry(QtCore.QRect(100, 50, 221, 51))
        self.sensor_in_temp_label.setGeometry(QtCore.QRect(first_row, first_column, 442, 102))
        self.sensor_in_temp_label.setStyleSheet("font: 75 35pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_in_temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_temp_label.setObjectName("sensor_in_temp_label")
        
        self.sensor_in_humi = QtWidgets.QLabel(Form)
        self.sensor_in_humi.setGeometry(QtCore.QRect(second_row, first_column, 442, 242))
        self.sensor_in_humi.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_in_humi.setText("")
        self.sensor_in_humi.setObjectName("sensor_in_humi")
        self.sensor_in_humi_value = QtWidgets.QLabel(Form)
        self.sensor_in_humi_value.setGeometry(QtCore.QRect(second_row + 10, first_column + 120, 402, 102))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_in_humi_value.setFont(font)
        self.sensor_in_humi_value.setStyleSheet("font: 81 35pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_in_humi_value.setText("")
        self.sensor_in_humi_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_humi_value.setObjectName("sensor_in_humi_value")
        self.sensor_in_humi_label = QtWidgets.QLabel(Form)
        self.sensor_in_humi_label.setGeometry(QtCore.QRect(second_row, first_column, 442, 102))
        self.sensor_in_humi_label.setStyleSheet("font: 75 35pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_in_humi_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_humi_label.setObjectName("sensor_in_humi_label")
        
        self.sensor_in_light = QtWidgets.QLabel(Form)
        self.sensor_in_light.setGeometry(QtCore.QRect(third_row, first_column, 442, 242))
        self.sensor_in_light.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_in_light.setText("")
        self.sensor_in_light.setObjectName("sensor_in_light")
        self.sensor_in_light_value = QtWidgets.QLabel(Form)
        self.sensor_in_light_value.setGeometry(QtCore.QRect(third_row + 10, first_column + 120, 402, 102))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_in_light_value.setFont(font)
        self.sensor_in_light_value.setStyleSheet("font: 81 35pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_in_light_value.setText("")
        self.sensor_in_light_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_light_value.setObjectName("sensor_in_light_value")
        self.sensor_in_light_label = QtWidgets.QLabel(Form)
        self.sensor_in_light_label.setGeometry(QtCore.QRect(third_row, first_column, 442, 102))
        self.sensor_in_light_label.setStyleSheet("font: 75 35pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_in_light_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_light_label.setObjectName("sensor_in_light_label")
        
        self.sensor_in_press = QtWidgets.QLabel(Form)
        #self.sensor_in_press.setGeometry(QtCore.QRect(100, 50, 221, 121))
        self.sensor_in_press.setGeometry(QtCore.QRect(first_row, second_column, 442, 242))
        self.sensor_in_press.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_in_press.setText("")
        self.sensor_in_press.setObjectName("sensor_in_press")
        self.sensor_in_press_value = QtWidgets.QLabel(Form)
        #self.sensor_in_press_value.setGeometry(QtCore.QRect(110, 110, 201, 51))
        self.sensor_in_press_value.setGeometry(QtCore.QRect(first_row + 10, second_column + 120, 402, 102))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_in_press_value.setFont(font)
        self.sensor_in_press_value.setStyleSheet("font: 81 35pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_in_press_value.setText("")
        self.sensor_in_press_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_press_value.setObjectName("sensor_in_press_value")
        self.sensor_in_press_label = QtWidgets.QLabel(Form)
        #self.sensor_in_press_label.setGeometry(QtCore.QRect(100, 50, 221, 51))
        self.sensor_in_press_label.setGeometry(QtCore.QRect(first_row, second_column, 442, 102))
        self.sensor_in_press_label.setStyleSheet("font: 75 35pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_in_press_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_press_label.setObjectName("sensor_in_press_label")
        
        self.sensor_in_gas = QtWidgets.QLabel(Form)
        self.sensor_in_gas.setGeometry(QtCore.QRect(second_row, second_column, 442, 242))
        self.sensor_in_gas.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_in_gas.setText("")
        self.sensor_in_gas.setObjectName("sensor_in_gas")
        self.sensor_in_gas_value = QtWidgets.QLabel(Form)
        self.sensor_in_gas_value.setGeometry(QtCore.QRect(second_row + 10, second_column + 120, 402, 102))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_in_gas_value.setFont(font)
        self.sensor_in_gas_value.setStyleSheet("font: 81 35pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_in_gas_value.setText("")
        self.sensor_in_gas_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_gas_value.setObjectName("sensor_in_gas_value")
        self.sensor_in_gas_label = QtWidgets.QLabel(Form)
        self.sensor_in_gas_label.setGeometry(QtCore.QRect(second_row, second_column, 442, 102))
        self.sensor_in_gas_label.setStyleSheet("font: 75 35pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_in_gas_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_gas_label.setObjectName("sensor_in_gas_label")
        
        self.sensor_co2 = QtWidgets.QLabel(Form)
        self.sensor_co2.setGeometry(QtCore.QRect(third_row, second_column, 442, 242))
        self.sensor_co2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_co2.setText("")
        self.sensor_co2.setObjectName("sensor_co2")
        self.sensor_co2_value = QtWidgets.QLabel(Form)
        self.sensor_co2_value.setGeometry(QtCore.QRect(third_row + 10, second_column + 120, 402, 102))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_co2_value.setFont(font)
        self.sensor_co2_value.setStyleSheet("font: 81 35pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_co2_value.setText("")
        self.sensor_co2_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_co2_value.setObjectName("sensor_co2_value")
        self.sensor_co2_label = QtWidgets.QLabel(Form)
        self.sensor_co2_label.setGeometry(QtCore.QRect(third_row, second_column, 442, 102))
        self.sensor_co2_label.setStyleSheet("font: 75 35pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_co2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_co2_label.setObjectName("sensor_co2_label")
        
        self.sensor_soil = QtWidgets.QLabel(Form)
        self.sensor_soil.setGeometry(QtCore.QRect(first_row, third_column, 442, 242))
        self.sensor_soil.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_soil.setText("")
        self.sensor_soil.setObjectName("sensor_soil")
        self.sensor_soil_value = QtWidgets.QLabel(Form)
        self.sensor_soil_value.setGeometry(QtCore.QRect(first_row + 10, third_column + 120, 402, 102))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_soil_value.setFont(font)
        self.sensor_soil_value.setStyleSheet("font: 81 35pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_soil_value.setText("")
        self.sensor_soil_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_soil_value.setObjectName("sensor_soil_value")
        self.sensor_soil_label = QtWidgets.QLabel(Form)
        self.sensor_soil_label.setGeometry(QtCore.QRect(first_row, third_column, 442, 102))
        self.sensor_soil_label.setStyleSheet("font: 75 35pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_soil_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_soil_label.setObjectName("sensor_soil_label")
        
        self.sensor_waterlevel = QtWidgets.QLabel(Form)
        self.sensor_waterlevel.setGeometry(QtCore.QRect(second_row, third_column, 442, 242))
        self.sensor_waterlevel.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_waterlevel.setText("")
        self.sensor_waterlevel.setObjectName("sensor_waterlevel")
        self.sensor_waterlevel_value = QtWidgets.QLabel(Form)
        self.sensor_waterlevel_value.setGeometry(QtCore.QRect(second_row + 10, third_column + 120, 402, 102))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_waterlevel_value.setFont(font)
        self.sensor_waterlevel_value.setStyleSheet("font: 81 35pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_waterlevel_value.setText("")
        self.sensor_waterlevel_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_waterlevel_value.setObjectName("sensor_waterlevel_value")
        self.sensor_waterlevel_label = QtWidgets.QLabel(Form)
        self.sensor_waterlevel_label.setGeometry(QtCore.QRect(second_row, third_column, 442, 102))
        self.sensor_waterlevel_label.setStyleSheet("font: 75 35pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_waterlevel_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_waterlevel_label.setObjectName("sensor_waterlevel_label")
        
        self.sensor_in_window = QtWidgets.QLabel(Form)
        self.sensor_in_window.setGeometry(QtCore.QRect(third_row, third_column, 442, 242))
        self.sensor_in_window.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 4px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_in_window.setText("")
        self.sensor_in_window.setObjectName("sensor_in_window")
        self.sensor_in_window_value = QtWidgets.QLabel(Form)
        self.sensor_in_window_value.setGeometry(QtCore.QRect(third_row + 20, third_column + 120, 402, 102))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(35)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_in_window_value.setFont(font)
        self.sensor_in_window_value.setStyleSheet("font: 81 35pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_in_window_value.setText("")
        self.sensor_in_window_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_window_value.setObjectName("sensor_in_window_value")
        self.sensor_in_window_label = QtWidgets.QLabel(Form)
        self.sensor_in_window_label.setGeometry(QtCore.QRect(third_row, third_column, 442, 102))
        self.sensor_in_window_label.setStyleSheet("font: 75 35pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_in_window_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_in_window_label.setObjectName("sensor_in_window_label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sensor_in_temp_label.setText(_translate("Form", "Temp"))
        self.sensor_in_humi_label.setText(_translate("Form", "Humi"))
        self.sensor_in_light_label.setText(_translate("Form", "Light"))
        self.sensor_in_press_label.setText(_translate("Form", "Pressure"))
        self.sensor_in_gas_label.setText(_translate("Form", "Air Quality"))
        self.sensor_co2_label.setText(_translate("Form", "CO2"))
        self.sensor_soil_label.setText(_translate("Form", "Soil Moisture"))
        self.sensor_waterlevel_label.setText(_translate("Form", "Water Level"))
        self.sensor_in_window_label.setText(_translate("Form", "Window"))
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
