# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/page_option.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1000, 580)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sensor_ec_value = QtWidgets.QLabel(Form)
        self.sensor_ec_value.setGeometry(QtCore.QRect(750, 110, 201, 51))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_ec_value.setFont(font)
        self.sensor_ec_value.setStyleSheet("font: 81 18pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_ec_value.setText("")
        self.sensor_ec_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_ec_value.setObjectName("sensor_ec_value")
        self.sensor_ec_label = QtWidgets.QLabel(Form)
        self.sensor_ec_label.setGeometry(QtCore.QRect(740, 50, 221, 51))
        self.sensor_ec_label.setStyleSheet("font: 75 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_ec_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_ec_label.setObjectName("sensor_ec_label")
        self.cooler_circle = QtWidgets.QLabel(Form)
        self.cooler_circle.setGeometry(QtCore.QRect(29, 47, 100, 100))
        self.cooler_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 50px;")
        self.cooler_circle.setText("")
        self.cooler_circle.setObjectName("cooler_circle")
        self.cooler_icon = QtWidgets.QLabel(Form)
        self.cooler_icon.setGeometry(QtCore.QRect(44, 62, 71, 71))
        self.cooler_icon.setStyleSheet("border-image: url(:/images/images/cooler.png);")
        self.cooler_icon.setText("")
        self.cooler_icon.setObjectName("cooler_icon")
        self.cooler_slide = QtWidgets.QLabel(Form)
        self.cooler_slide.setGeometry(QtCore.QRect(150, 59, 150, 75))
        self.cooler_slide.setStyleSheet("")
        self.cooler_slide.setText("")
        self.cooler_slide.setObjectName("cooler_slide")
        self.heater_circle = QtWidgets.QLabel(Form)
        self.heater_circle.setGeometry(QtCore.QRect(361, 49, 100, 100))
        self.heater_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 50px;")
        self.heater_circle.setText("")
        self.heater_circle.setObjectName("heater_circle")
        self.heater_icon = QtWidgets.QLabel(Form)
        self.heater_icon.setGeometry(QtCore.QRect(376, 64, 71, 71))
        self.heater_icon.setStyleSheet("border-image: url(:/images/images/heater.png);")
        self.heater_icon.setText("")
        self.heater_icon.setObjectName("heater_icon")
        self.heater_slide = QtWidgets.QLabel(Form)
        self.heater_slide.setGeometry(QtCore.QRect(480, 61, 150, 75))
        self.heater_slide.setStyleSheet("")
        self.heater_slide.setText("")
        self.heater_slide.setObjectName("heater_slide")
        self.nutrientsolution_pump_slide = QtWidgets.QLabel(Form)
        self.nutrientsolution_pump_slide.setGeometry(QtCore.QRect(150, 234, 150, 75))
        self.nutrientsolution_pump_slide.setStyleSheet("")
        self.nutrientsolution_pump_slide.setText("")
        self.nutrientsolution_pump_slide.setObjectName("nutrientsolution_pump_slide")
        self.nutrientsolution_pump_circle = QtWidgets.QLabel(Form)
        self.nutrientsolution_pump_circle.setGeometry(QtCore.QRect(30, 222, 100, 100))
        self.nutrientsolution_pump_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 50px;")
        self.nutrientsolution_pump_circle.setText("")
        self.nutrientsolution_pump_circle.setObjectName("nutrientsolution_pump_circle")
        self.nutrientsolution_pump_icon = QtWidgets.QLabel(Form)
        self.nutrientsolution_pump_icon.setGeometry(QtCore.QRect(45, 237, 71, 71))
        self.nutrientsolution_pump_icon.setStyleSheet("border-image: url(:/images/images/nu_pump.png);")
        self.nutrientsolution_pump_icon.setText("")
        self.nutrientsolution_pump_icon.setObjectName("nutrientsolution_pump_icon")
        self.co2_pump_circle = QtWidgets.QLabel(Form)
        self.co2_pump_circle.setGeometry(QtCore.QRect(29, 383, 100, 100))
        self.co2_pump_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 50px;")
        self.co2_pump_circle.setText("")
        self.co2_pump_circle.setObjectName("co2_pump_circle")
        self.co2_pump_slide = QtWidgets.QLabel(Form)
        self.co2_pump_slide.setGeometry(QtCore.QRect(149, 395, 150, 75))
        self.co2_pump_slide.setStyleSheet("")
        self.co2_pump_slide.setText("")
        self.co2_pump_slide.setObjectName("co2_pump_slide")
        self.co2_pump_icon = QtWidgets.QLabel(Form)
        self.co2_pump_icon.setGeometry(QtCore.QRect(49, 400, 61, 61))
        self.co2_pump_icon.setStyleSheet("border-image: url(:/images/images/co2.png);")
        self.co2_pump_icon.setText("")
        self.co2_pump_icon.setObjectName("co2_pump_icon")
        self.ph_pump_circle = QtWidgets.QLabel(Form)
        self.ph_pump_circle.setGeometry(QtCore.QRect(360, 385, 100, 101))
        self.ph_pump_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 50px;")
        self.ph_pump_circle.setText("")
        self.ph_pump_circle.setObjectName("ph_pump_circle")
        self.ph_pump_icon = QtWidgets.QLabel(Form)
        self.ph_pump_icon.setGeometry(QtCore.QRect(374, 400, 71, 71))
        self.ph_pump_icon.setStyleSheet("border-image: url(:/images/images/ph.png);")
        self.ph_pump_icon.setText("")
        self.ph_pump_icon.setObjectName("ph_pump_icon")
        self.ph_combo = QtWidgets.QComboBox(Form)
        self.ph_combo.setGeometry(QtCore.QRect(480, 390, 150, 45))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ph_combo.setFont(font)
        self.ph_combo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ph_combo.setStyleSheet("font: 12pt \"나눔스퀘어\";")
        self.ph_combo.setEditable(True)
        self.ph_combo.setCurrentText("")
        self.ph_combo.setObjectName("ph_combo")
        self.ph_button = QtWidgets.QPushButton(Form)
        self.ph_button.setGeometry(QtCore.QRect(480, 450, 150, 35))
        self.ph_button.setStyleSheet("QPushButton:hover\n"
"{ \n"
"    background-color: rgb(0, 135, 68);\n"
"    border-radius: 15px;\n"
"    font: 75 15pt \"Arial\";\n"
"    color: white;  \n"
"}\n"
"\n"
"QPushButton\n"
"{ \n"
"    border-radius: 15px;\n"
"    border: 1px solid rgb(0, 135, 68);\n"
"    font: 75 15pt \"나눔스퀘어 Bold\";\n"
"    color: rgb(0, 135, 68);\n"
"}\n"
"")
        self.ph_button.setObjectName("ph_button")
        self.sensor_ec = QtWidgets.QLabel(Form)
        self.sensor_ec.setGeometry(QtCore.QRect(740, 50, 221, 121))
        self.sensor_ec.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_ec.setText("")
        self.sensor_ec.setObjectName("sensor_ec")
        self.sensor_ph_label = QtWidgets.QLabel(Form)
        self.sensor_ph_label.setGeometry(QtCore.QRect(740, 210, 221, 51))
        self.sensor_ph_label.setStyleSheet("font: 75 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_ph_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_ph_label.setObjectName("sensor_ph_label")
        self.sensor_ph = QtWidgets.QLabel(Form)
        self.sensor_ph.setGeometry(QtCore.QRect(740, 210, 221, 121))
        self.sensor_ph.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_ph.setText("")
        self.sensor_ph.setObjectName("sensor_ph")
        self.sensor_ph_value = QtWidgets.QLabel(Form)
        self.sensor_ph_value.setGeometry(QtCore.QRect(750, 270, 201, 51))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_ph_value.setFont(font)
        self.sensor_ph_value.setStyleSheet("font: 81 18pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_ph_value.setText("")
        self.sensor_ph_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_ph_value.setObjectName("sensor_ph_value")
        self.sensor_nutrient_level_label = QtWidgets.QLabel(Form)
        self.sensor_nutrient_level_label.setGeometry(QtCore.QRect(740, 370, 221, 51))
        self.sensor_nutrient_level_label.setStyleSheet("font: 75 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 135, 68);")
        self.sensor_nutrient_level_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_nutrient_level_label.setObjectName("sensor_nutrient_level_label")
        self.sensor_nutrient_level = QtWidgets.QLabel(Form)
        self.sensor_nutrient_level.setGeometry(QtCore.QRect(740, 370, 221, 121))
        self.sensor_nutrient_level.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-style: solid;\n"
"border-width: 1px;\n"
"border-color: rgb(0, 135, 68);")
        self.sensor_nutrient_level.setText("")
        self.sensor_nutrient_level.setObjectName("sensor_nutrient_level")
        self.sensor_nutrientlevel_value = QtWidgets.QLabel(Form)
        self.sensor_nutrientlevel_value.setGeometry(QtCore.QRect(750, 430, 201, 51))
        font = QtGui.QFont()
        font.setFamily("나눔스퀘어 ExtraBold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.sensor_nutrientlevel_value.setFont(font)
        self.sensor_nutrientlevel_value.setStyleSheet("font: 81 18pt \"나눔스퀘어 ExtraBold\";\n"
"color: rgb(0, 135, 68);")
        self.sensor_nutrientlevel_value.setText("")
        self.sensor_nutrientlevel_value.setAlignment(QtCore.Qt.AlignCenter)
        self.sensor_nutrientlevel_value.setObjectName("sensor_nutrientlevel_value")
        self.nutrient_pump_icon = QtWidgets.QLabel(Form)
        self.nutrient_pump_icon.setGeometry(QtCore.QRect(374, 235, 71, 71))
        self.nutrient_pump_icon.setStyleSheet("border-image: url(:/images/images/ab_pump.png);")
        self.nutrient_pump_icon.setText("")
        self.nutrient_pump_icon.setObjectName("nutrient_pump_icon")
        self.nutrient_pump_circle = QtWidgets.QLabel(Form)
        self.nutrient_pump_circle.setGeometry(QtCore.QRect(360, 220, 100, 100))
        self.nutrient_pump_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 50px;")
        self.nutrient_pump_circle.setText("")
        self.nutrient_pump_circle.setObjectName("nutrient_pump_circle")
        self.nutrient_pump_slide = QtWidgets.QLabel(Form)
        self.nutrient_pump_slide.setGeometry(QtCore.QRect(480, 232, 150, 75))
        self.nutrient_pump_slide.setStyleSheet("")
        self.nutrient_pump_slide.setText("")
        self.nutrient_pump_slide.setObjectName("nutrient_pump_slide")
        self.nutrient_pump_circle.raise_()
        self.sensor_nutrient_level.raise_()
        self.co2_pump_circle.raise_()
        self.sensor_ph.raise_()
        self.sensor_ec.raise_()
        self.nutrientsolution_pump_circle.raise_()
        self.sensor_ec_value.raise_()
        self.cooler_circle.raise_()
        self.cooler_slide.raise_()
        self.heater_circle.raise_()
        self.heater_slide.raise_()
        self.nutrientsolution_pump_slide.raise_()
        self.co2_pump_slide.raise_()
        self.ph_pump_circle.raise_()
        self.ph_combo.raise_()
        self.ph_button.raise_()
        self.sensor_ec_label.raise_()
        self.sensor_ph_label.raise_()
        self.sensor_ph_value.raise_()
        self.cooler_icon.raise_()
        self.heater_icon.raise_()
        self.ph_pump_icon.raise_()
        self.co2_pump_icon.raise_()
        self.sensor_nutrient_level_label.raise_()
        self.sensor_nutrientlevel_value.raise_()
        self.nutrient_pump_slide.raise_()
        self.nutrientsolution_pump_icon.raise_()
        self.nutrient_pump_icon.raise_()

        self.retranslateUi(Form)
        self.ph_combo.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sensor_ec_label.setText(_translate("Form", "EC"))
        self.ph_button.setText(_translate("Form", "Action"))
        self.sensor_ph_label.setText(_translate("Form", "pH"))
        self.sensor_nutrient_level_label.setText(_translate("Form", "Nutrient Level"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
