# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './source/widgets/ui/page_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        path = os.path.dirname(os.path.abspath(__file__))
        self.titlebar_label = QtWidgets.QLabel(Form)
        self.titlebar_label.setAlignment(QtCore.Qt.AlignVCenter)
        self.titlebar_label.setGeometry(QtCore.QRect(0, 990, 1920, 90))
        self.titlebar_label.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"font: 81 55pt \"나눔스퀘어 ExtraBold\";\n"
"color: white\n"
"")
        self.titlebar_label.setObjectName("titlebar_label")
        self.logo_icon = QtWidgets.QLabel(Form)
        self.logo_icon.setGeometry(QtCore.QRect(18, 1006, 60, 60))
        self.logo_icon.setStyleSheet(f"border-image: url('{path}/images/leaf.png');")
        self.logo_icon.setText("")
        self.logo_icon.setObjectName("logo_icon")
        
        self.sen_button = QtWidgets.QPushButton(Form)
        self.sen_button.setGeometry(QtCore.QRect(500, 1007, 210, 61))
        self.sen_button.setStyleSheet("QPushButton\n"
"{ \n"
"    background-color: rgba(0, 0, 0, 0%);\n"
"    border-radius: 15px;\n"
"    border: 4px solid rgb(255,255,255);\n"
"    font: 75 25pt \"Arial\";\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n")
        self.sen_button.setObjectName("sen_button")
        
        self.act_button = QtWidgets.QPushButton(Form)
        self.act_button.setGeometry(QtCore.QRect(725, 1007, 210, 61))
        self.act_button.setStyleSheet("QPushButton\n"
"{ \n"
"    background-color: rgba(0, 0, 0, 0%);\n"
"    border-radius: 15px;\n"
"    border: 4px solid rgb(255,255,255);\n"
"    font: 75 25pt \"Arial\";\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{ \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(0, 135, 68);\n"
"    font: 75 17pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:focus:checked\n"
"{ \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(0, 135, 68);  \n"
"    font: 75 17pt \"Arial\";\n"
"}")
        self.act_button.setObjectName("act_button")
        
        self.cam_button = QtWidgets.QPushButton(Form)
        self.cam_button.setGeometry(QtCore.QRect(950, 1007, 210, 61))
        self.cam_button.setStyleSheet("QPushButton\n"
"{ \n"
"    background-color: rgba(0, 0, 0, 0%);\n"
"    border-radius: 15px;\n"
"    border: 4px solid rgb(255,255,255);\n"
"    font: 75 25pt \"Arial\";\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{ \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(0, 135, 68);\n"
"    font: 75 17pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:focus:checked\n"
"{ \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(0, 135, 68);  \n"
"    font: 75 17pt \"Arial\";\n"
"}")
        self.cam_button.setObjectName("cam_button")
        
        self.widgets = QtWidgets.QStackedWidget(Form)
        self.widgets.setGeometry(QtCore.QRect(0, 100, 1920, 860))
        self.widgets.setObjectName("widgets")
        self.set_button = QtWidgets.QPushButton(Form)
        self.set_button.setGeometry(QtCore.QRect(1175, 1007, 210, 61))
        self.set_button.setStyleSheet("QPushButton\n"
"{ \n"
"    background-color: rgba(0, 0, 0, 0%);\n"
"    border-radius: 15px;\n"
"    border: 4px solid rgb(255,255,255);\n"
"    font: 75 25pt \"Arial\";\n"
"    color: rgb(255,255,255);\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{ \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(0, 135, 68);\n"
"    font: 75 17pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:focus:checked\n"
"{ \n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 15px;\n"
"    color: rgb(0, 135, 68);  \n"
"    font: 75 17pt \"Arial\";\n"
"}")
        self.port_label = QtWidgets.QLabel(Form)
        self.port_label.setGeometry(QtCore.QRect(40, 40, 700, 70))
        self.port_label.setStyleSheet("color: rgb(0, 135, 68);\n"
"font: 75 60pt \"Arial\";")
        self.port_label.setObjectName("port_label")
        self.pow_button = QtWidgets.QPushButton(Form)
        self.pow_button.setGeometry(QtCore.QRect(1810, 1002, 75, 65))
        self.pow_button.setStyleSheet("QPushButton\n"
"{ \n"
"color: rgb(0, 135, 68);\n"
f"border-image: url('{path}/images/power_on.png');"
"}\n"
"\n"
"QPushButton:hover\n"
"{ \n"
f"border-image: url('{path}/images/power.png');"
"}\n"
"\n")
        self.pow_button.setText("")
        self.pow_button.setObjectName("pow_button")        

        self.retranslateUi(Form)
        # self.widgets.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        # Form.setWindowTitle(_translate("Form", "Form"))
        self.titlebar_label.setText(_translate("Form", "     SmartFarm"))        
        self.sen_button.setText(_translate("Form", "Sensor"))
        self.act_button.setText(_translate("Form", "Actuator"))
        self.cam_button.setText(_translate("Form", "Camera"))
        self.set_button.setText(_translate("Form", "Setting"))
        self.port_label.setText(_translate("Form", "No conncetion..."))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
