# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/page_option.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 860)
        Form.setStyleSheet("QWidget#Form\n"
"{\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.camera_area = QtWidgets.QLabel(Form)
        self.camera_area.setGeometry(QtCore.QRect(425, 57, 1370, 782))
        self.camera_area.setStyleSheet("border-radius : 5px;\n"
"border: 8px solid rgb(0, 135, 68);\n"
"")
        self.camera_area.setText("")
        self.camera_area.setObjectName("camera_area")
        
        self.video_label = QtWidgets.QLabel(Form)
        self.video_label.setGeometry(QtCore.QRect(438, 70, 1344, 756))
        
        self.grey_button = QtWidgets.QPushButton(Form)
        self.grey_button.setGeometry(QtCore.QRect(70, 57, 281, 120))
        self.grey_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.grey_button.setStyleSheet("QPushButton:hover\n"
"{ \n"
"    background-color: rgb(0, 135, 68);\n"
"    border-radius: 15px;\n"
"    font: 75 35pt \"Arial\";\n"
"    color: white;  \n"
"}\n"
"\n"
"QPushButton\n"
"{ \n"
"    border-radius: 15px;\n"
"    border: 4px solid rgb(0, 135, 68);\n"
"    font: 75 35pt \"나눔스퀘어 Bold\";\n"
"    color: rgb(0, 135, 68);\n"
"}\n"
"")
        self.grey_button.setObjectName("grey_button")
        
        self.color_button = QtWidgets.QPushButton(Form)
        self.color_button.setGeometry(QtCore.QRect(70, 257, 281, 120))
        self.color_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.color_button.setStyleSheet("QPushButton:hover\n"
"{ \n"
"    background-color: rgb(0, 135, 68);\n"
"    border-radius: 15px;\n"
"    font: 75 35pt \"Arial\";\n"
"    color: white;  \n"
"}\n"
"\n"
"QPushButton\n"
"{ \n"
"    border-radius: 15px;\n"
"    border: 4px solid rgb(0, 135, 68);\n"
"    font: 75 35pt \"나눔스퀘어 Bold\";\n"
"    color: rgb(0, 135, 68);\n"
"}\n"
"")
        self.color_button.setObjectName("color_button")
        
        self.canny_button = QtWidgets.QPushButton(Form)
        self.canny_button.setGeometry(QtCore.QRect(70, 457, 281, 120))
        self.canny_button.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.canny_button.setStyleSheet("QPushButton:hover\n"
"{ \n"
"    background-color: rgb(0, 135, 68);\n"
"    border-radius: 15px;\n"
"    font: 75 35pt \"Arial\";\n"
"    color: white;  \n"
"}\n"
"\n"
"QPushButton\n"
"{ \n"
"    border-radius: 15px;\n"
"    border: 4px solid rgb(0, 135, 68);\n"
"    font: 75 35pt \"나눔스퀘어 Bold\";\n"
"    color: rgb(0, 135, 68);\n"
"}\n"
"")
        self.canny_button.setObjectName("canny_button")
        
        self.grey_button.raise_()
        self.color_button.raise_()
        self.canny_button.raise_()
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.grey_button.setText(_translate("Form", "Grey"))
        self.color_button.setText(_translate("Form", "Color"))
        self.canny_button.setText(_translate("Form", "Canny"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
