# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './widgets/ui/page_actuator.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 860)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        path = os.path.dirname(os.path.abspath(__file__))
        
        self.water_icon = QtWidgets.QLabel(Form)
        self.water_icon.setGeometry(QtCore.QRect(80, 85, 160, 160))
        self.water_icon.setStyleSheet(f"border-image: url('{path}/images/water.png');")
        self.water_icon.setText("")
        self.water_icon.setObjectName("water_icon")
        self.water_circle = QtWidgets.QLabel(Form)
        self.water_circle.setGeometry(QtCore.QRect(60, 65, 200, 200))
        self.water_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 10px;")
        self.water_circle.setText("")
        self.water_circle.setObjectName("water_circle")
        self.water_label = QtWidgets.QLabel(Form)
        self.water_label.setGeometry(QtCore.QRect(290, 60, 270, 55))
        self.water_label.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.water_label.setObjectName("water_label")
        self.water_value = QtWidgets.QLabel(Form)
        self.water_value.setGeometry(QtCore.QRect(300, 120, 270, 55))
        self.water_value.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.water_value.setObjectName("water_value")
        self.water_slide = QtWidgets.QLabel(Form)
        self.water_slide.setGeometry(QtCore.QRect(290, 180, 270, 86))
        self.water_slide.setStyleSheet("")
        self.water_slide.setText("")
        self.water_slide.setObjectName("water_slide")
        
        self.lfan_icon = QtWidgets.QLabel(Form)
        self.lfan_icon.setGeometry(QtCore.QRect(80, 345, 160, 160))
        self.lfan_icon.setStyleSheet(f"border-image: url('{path}/images/fan.png');")
        self.lfan_icon.setText("")
        self.lfan_icon.setObjectName("lfan_icon")
        self.lfan_circle = QtWidgets.QLabel(Form)
        self.lfan_circle.setGeometry(QtCore.QRect(60, 325, 200, 200))
        self.lfan_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 10px;")
        self.lfan_circle.setText("")
        self.lfan_circle.setObjectName("lfan_circle")
        self.lfan_label = QtWidgets.QLabel(Form)
        self.lfan_label.setGeometry(QtCore.QRect(290, 320, 270, 55))
        self.lfan_label.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.lfan_label.setObjectName("lfan_label")
        self.lfan_value = QtWidgets.QLabel(Form)
        self.lfan_value.setGeometry(QtCore.QRect(300, 380, 270, 55))
        self.lfan_value.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.lfan_value.setObjectName("lfan_value")
        self.lfan_slide = QtWidgets.QLabel(Form)
        self.lfan_slide.setGeometry(QtCore.QRect(290, 440, 270, 86))
        self.lfan_slide.setStyleSheet("")
        self.lfan_slide.setText("")
        self.lfan_slide.setObjectName("lfan_slide")
        
        self.rfan_icon = QtWidgets.QLabel(Form)
        self.rfan_icon.setGeometry(QtCore.QRect(80, 615, 160, 160))
        self.rfan_icon.setStyleSheet(f"border-image: url('{path}/images/fan.png');")
        self.rfan_icon.setText("")
        self.rfan_icon.setObjectName("rfan_icon")
        self.rfan_circle = QtWidgets.QLabel(Form)
        self.rfan_circle.setGeometry(QtCore.QRect(60, 595, 200, 200))
        self.rfan_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 10px;")
        self.rfan_circle.setText("")
        self.rfan_circle.setObjectName("rfan_circle")
        self.rfan_label = QtWidgets.QLabel(Form)
        self.rfan_label.setGeometry(QtCore.QRect(290, 590, 270, 57))
        self.rfan_label.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.rfan_label.setObjectName("rfan_label")
        self.rfan_value = QtWidgets.QLabel(Form)
        self.rfan_value.setGeometry(QtCore.QRect(300, 650, 270, 55))
        self.rfan_value.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.rfan_value.setObjectName("rfan_value")
        self.rfan_slide = QtWidgets.QLabel(Form)
        self.rfan_slide.setGeometry(QtCore.QRect(290, 710, 270, 86))
        self.rfan_slide.setStyleSheet("")
        self.rfan_slide.setText("")
        self.rfan_slide.setObjectName("rfan_slide")        
        
        self.window_icon = QtWidgets.QLabel(Form)
        self.window_icon.setGeometry(QtCore.QRect(670, 85, 160, 160))
        self.window_icon.setStyleSheet(f"border-image: url('{path}/images/blind.png');")
        self.window_icon.setText("")
        self.window_icon.setObjectName("window_icon")
        self.window_circle = QtWidgets.QLabel(Form)
        self.window_circle.setGeometry(QtCore.QRect(650, 65, 200, 200))
        self.window_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 10px;")
        self.window_circle.setText("")
        self.window_circle.setObjectName("window_circle")
        self.window_label = QtWidgets.QLabel(Form)
        self.window_label.setGeometry(QtCore.QRect(890, 60, 270, 42))
        self.window_label.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.window_label.setObjectName("window_label")
        self.window_value = QtWidgets.QLabel(Form)
        self.window_value.setGeometry(QtCore.QRect(900, 120, 270, 55))
        self.window_value.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.window_value.setObjectName("window_value")
        self.window_slide = QtWidgets.QLabel(Form)
        self.window_slide.setGeometry(QtCore.QRect(890, 180, 270, 86))
        self.window_slide.setStyleSheet("")
        self.window_slide.setText("")
        self.window_slide.setObjectName("window_slide")
        
        self.heater_icon = QtWidgets.QLabel(Form)
        self.heater_icon.setGeometry(QtCore.QRect(670, 345, 160, 160))
        self.heater_icon.setStyleSheet(f"border-image: url('{path}/images/heater.png');")
        self.heater_icon.setText("")
        self.heater_icon.setObjectName("heater_icon")
        self.heater_circle = QtWidgets.QLabel(Form)
        self.heater_circle.setGeometry(QtCore.QRect(650, 325, 200, 200))
        self.heater_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 10px;")
        self.heater_circle.setText("")
        self.heater_circle.setObjectName("heater_circle")
        self.heater_label = QtWidgets.QLabel(Form)
        self.heater_label.setGeometry(QtCore.QRect(890, 320, 270, 55))
        self.heater_label.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.heater_label.setObjectName("heater_label")
        self.heater_value = QtWidgets.QLabel(Form)
        self.heater_value.setGeometry(QtCore.QRect(900, 380, 270, 55))
        self.heater_value.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.heater_value.setObjectName("heater_value")
        self.heater_slide = QtWidgets.QLabel(Form)
        self.heater_slide.setGeometry(QtCore.QRect(890, 440, 270, 86))
        self.heater_slide.setStyleSheet("")
        self.heater_slide.setText("")
        self.heater_slide.setObjectName("heater_slide")
        
        self.cooler_icon = QtWidgets.QLabel(Form)
        self.cooler_icon.setGeometry(QtCore.QRect(670, 615, 160, 160))
        self.cooler_icon.setStyleSheet(f"border-image: url('{path}/images/cooler.png');")
        self.cooler_icon.setText("")
        self.cooler_icon.setObjectName("cooler_icon")
        self.cooler_circle = QtWidgets.QLabel(Form)
        self.cooler_circle.setGeometry(QtCore.QRect(650, 595, 200, 200))
        self.cooler_circle.setStyleSheet("background-color: rgb(0, 135, 68);\n"
"border-radius: 10px;")
        self.cooler_circle.setText("")
        self.cooler_circle.setObjectName("cooler_circle")
        self.cooler_label = QtWidgets.QLabel(Form)
        self.cooler_label.setGeometry(QtCore.QRect(890, 590, 270, 55))
        self.cooler_label.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.cooler_label.setObjectName("cooler_label")
        self.cooler_value = QtWidgets.QLabel(Form)
        self.cooler_value.setGeometry(QtCore.QRect(900, 650, 270, 55))
        self.cooler_value.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.cooler_value.setObjectName("cooler_value")
        self.cooler_slide = QtWidgets.QLabel(Form)
        self.cooler_slide.setGeometry(QtCore.QRect(890, 710, 270, 90))
        self.cooler_slide.setStyleSheet("")
        self.cooler_slide.setText("")
        self.cooler_slide.setObjectName("cooler_slide")  
        
        self.rgb_title = QtWidgets.QLabel(Form)
        self.rgb_title.setGeometry(QtCore.QRect(1240, 60, 342, 42))
        self.rgb_title.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.rgb_title.setObjectName("rgb_title")
        self.color_label = QtWidgets.QLabel(Form)
        self.color_label.setGeometry(QtCore.QRect(1390, 135, 400, 330))
        self.color_label.setStyleSheet("background-color: black;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.color_label.setText("")
        self.color_label.setObjectName("color_label")
        
        self.red_text = QtWidgets.QLabel(Form)
        self.red_text.setGeometry(QtCore.QRect(1215, 510, 342, 42))
        self.red_text.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.red_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal,Form)
        self.red_slider.setRange(0,255)
        self.red_slider.setSingleStep(1)
        self.red_slider.setGeometry(1390,490,400,80)
        self.red_slider.setStyleSheet("""
                QSlider::groove:horizontal {
                border-radius: 1px;
                height: 15px;
                margin: 0px;
                background-color: rgb(200, 200, 200);
                }
                QSlider::groove:horizontal:hover {
                background-color: rgb(200, 200, 200);
                }
                QSlider::handle:horizontal {
                background-color: rgb(85, 170, 255);
                border: 10PX;
                height: 80px;
                width: 40px;
                margin: -20px 0px;
                border-radius: 20px;
                padding: 0px 0px;
                }
                QSlider::handle:horizontal:hover {
                background-color: rgb(155, 180, 255);
                }
                QSlider::handle:horizontal:pressed {
                background-color: rgb(65, 255, 195);
                }
        """)
        self.red_label = QtWidgets.QLabel(Form)
        self.red_label.setGeometry(QtCore.QRect(1800, 510, 342, 42))
        self.red_label.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.green_text = QtWidgets.QLabel(Form)
        self.green_text.setGeometry(QtCore.QRect(1215, 600, 342, 42))
        self.green_text.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.green_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal,Form)
        self.green_slider.setRange(0,255)
        self.green_slider.setSingleStep(1)
        self.green_slider.setGeometry(1390,580,400,80)
        self.green_slider.setStyleSheet("""
                QSlider::groove:horizontal {
                border-radius: 1px;
                height: 15px;
                margin: 0px;
                background-color: rgb(200, 200, 200);
                }
                QSlider::groove:horizontal:hover {
                background-color: rgb(200, 200, 200);
                }
                QSlider::handle:horizontal {
                background-color: rgb(85, 170, 255);
                border: 10PX;
                height: 80px;
                width: 40px;
                margin: -20px 0px;
                border-radius: 20px;
                padding: 0px 0px;
                }
                QSlider::handle:horizontal:hover {
                background-color: rgb(155, 180, 255);
                }
                QSlider::handle:horizontal:pressed {
                background-color: rgb(65, 255, 195);
                }
        """)
        self.green_label = QtWidgets.QLabel(Form)
        self.green_label.setGeometry(QtCore.QRect(1800, 600, 342, 42))
        self.green_label.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.blue_text = QtWidgets.QLabel(Form)
        self.blue_text.setGeometry(QtCore.QRect(1215, 690, 342, 42))
        self.blue_text.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        self.blue_slider = QtWidgets.QSlider(QtCore.Qt.Horizontal,Form)
        self.blue_slider.setRange(0,255)
        self.blue_slider.setSingleStep(1)
        self.blue_slider.setGeometry(1390,670,400,80)
        self.blue_slider.setStyleSheet("""
                QSlider::groove:horizontal {
                border-radius: 1px;
                height: 15px;
                margin: 0px;
                background-color: rgb(200, 200, 200);
                }
                QSlider::groove:horizontal:hover {
                background-color: rgb(200, 200, 200);
                }
                QSlider::handle:horizontal {
                background-color: rgb(85, 170, 255);
                border: 10PX;
                height: 80px;
                width: 40px;
                margin: -20px 0px;
                border-radius: 20px;
                padding: 0px 0px;
                }
                QSlider::handle:horizontal:hover {
                background-color: rgb(155, 180, 255);
                }
                QSlider::handle:horizontal:pressed {
                background-color: rgb(65, 255, 195);
                }
        """)
        self.blue_label = QtWidgets.QLabel(Form)
        self.blue_label.setGeometry(QtCore.QRect(1800, 690, 342, 42))
        self.blue_label.setStyleSheet("background-color: white;\n"
"font: 81 35pt \"Arial\";\n"
"color: rgb(0, 135, 68)\n"
"")
        # self.led_area = QtWidgets.QLabel(Form)
        # self.led_area.setGeometry(QtCore.QRect(1200, 64, 601, 431))
        # self.led_area.setStyleSheet("")
        # self.led_area.setText("")
        # self.led_area.setObjectName("led_area")
                
        self.set_button = QtWidgets.QPushButton(Form)
        self.set_button.setGeometry(QtCore.QRect(1640, 775, 222, 62))
        self.set_button.setStyleSheet("QPushButton:hover\n"
"{ \n"
"    background-color: rgb(0, 135, 68);\n"
"    border-radius: 15px;\n"
"    font: 75 35pt \"Arial\";\n"
"    color: white;  \n"
"}\n"
"\n"
"QPushButton\n"
"{ \n"
"    border-radius: 15px;\n"
"    border: 4px solid rgb(0, 135, 68);\n"
"    font: 75 35pt \"나눔스퀘어 Bold\";\n"
"    color: rgb(0, 135, 68);\n"
"}\n"
"")
        self.set_button.setObjectName("set_button")
        
        self.water_circle.raise_()
        self.water_icon.raise_()
        self.water_label.raise_()
        self.water_value.raise_()
        self.water_slide.raise_()        
        
        self.lfan_circle.raise_()
        self.lfan_icon.raise_()  
        self.lfan_label.raise_()
        self.lfan_value.raise_()
        self.lfan_slide.raise_()
        
        self.rfan_circle.raise_()
        self.rfan_icon.raise_()        
        self.rfan_label.raise_()
        self.rfan_value.raise_()
        self.rfan_slide.raise_()
        
        self.window_circle.raise_()
        self.window_icon.raise_()        
        self.window_label.raise_()
        self.window_value.raise_()
        self.window_slide.raise_()
        
        self.heater_circle.raise_()
        self.heater_icon.raise_()        
        self.heater_label.raise_()
        self.heater_value.raise_()
        self.heater_slide.raise_()
        
        self.cooler_circle.raise_()
        self.cooler_icon.raise_()        
        self.cooler_label.raise_()
        self.cooler_value.raise_()
        self.cooler_slide.raise_()
        
        #self.led_area.raise_()
        self.rgb_title.raise_()
        self.red_text.raise_()
        self.red_slider.raise_()
        self.red_label.raise_()
        self.green_text.raise_()
        self.green_slider.raise_()
        self.green_label.raise_()
        self.blue_text.raise_()
        self.blue_slider.raise_()
        self.blue_label.raise_()
        self.color_label.raise_()
        self.set_button.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.water_label.setText(_translate("Form", "Water Pump"))
        self.lfan_label.setText(_translate("Form", "Left Fan"))
        self.rfan_label.setText(_translate("Form", "Right Fan"))
        self.window_label.setText(_translate("Form", "Window"))
        self.heater_label.setText(_translate("Form", "Heater"))
        self.cooler_label.setText(_translate("Form", "Cooler"))
        self.water_value.setText(_translate("Form", "Off"))
        self.lfan_value.setText(_translate("Form", "Off"))
        self.rfan_value.setText(_translate("Form", "Off"))
        self.window_value.setText(_translate("Form", "0 %"))
        self.heater_value.setText(_translate("Form", "Off"))
        self.cooler_value.setText(_translate("Form", "Off"))
        self.rgb_title.setText(_translate("Form", "RGB LED BAR"))
        self.red_text.setText(_translate("Form", "RED"))
        self.red_label.setText(_translate("Form", "0"))
        self.green_text.setText(_translate("Form", "GREEN"))
        self.green_label.setText(_translate("Form", "0"))
        self.blue_text.setText(_translate("Form", "BLUE"))
        self.blue_label.setText(_translate("Form", "0"))
        self.set_button.setText(_translate("Form", "Set"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
